version: "3.9"

services:
  database:
    image: postgres:14
    container_name: melodb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - melodb-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@melodb:5432/postgres?schema=public"
    ports:
      - "3000:3000"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  melodb-volume:
    driver: local
